source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# Specify your gem's dependencies in CLI_Shoe_Love.gemspec
gem 'rspec'
gem 'pry'
gem 'require_all'
gem 'nokogiri'
gem 'httparty'
